#!/usr/bin/perl 
use strict;
use warnings;
use v5.10.0;

use JSON;
use MetaCPAN::Walker;
use MetaCPAN::Walker::Action::WriteSpec;
use MetaCPAN::Walker::Local::RPMSpec;
use MetaCPAN::Walker::Policy::InteractiveDistConfig;
use RPM::MetaCPAN;

my $rpm = RPM::MetaCPAN->new_with_options;

my %params = (
	%{ $rpm->configuration },
	dist_config => $rpm->dist_config,
);

my $walker = MetaCPAN::Walker->new(
	action => MetaCPAN::Walker::Action::WriteSpec->new(%params),
	local  => MetaCPAN::Walker::Local::RPMSpec->new(%params),
	policy => MetaCPAN::Walker::Policy::InteractiveDistConfig->new(%params),
);

$walker->walk_from_modules(@ARGV);

my $config = $rpm->dist_config->config;
my $json = JSON->new->utf8->pretty->canonical;
open (my $fh, '>', 'dists.new.json') or die "Could not open output: $!";
say $fh $json->encode($config);
